name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: "checks"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - name: fmt
      run: cargo fmt --all -- --check

    - name: Install base deps
      run: |
        sudo apt install --no-install-recommends -y libasound2-dev libdbus-1-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev

    - name: clippy
      run: cargo clippy --no-deps --all-targets -- -D warnings

    - name: Build with no default features
      run: cargo build --no-default-features

    - name: Build with default features
      run: |
        sudo apt install libpulse-dev
        cargo build
